<script lang="ts">
    import { ChevronLeft, DoorOpen, CircleCheckBig, Copy, Check, LoaderCircle, LogIn } from '@lucide/svelte'
    import { pb } from '$lib/config'

    /** Fields echoed back by the `rooms` collection on create.
     *  `join_code` and `admin_pin` are auto-generated by PocketBase;
     *  `admin_pin` is hidden in the API, so it never comes back here. */
    interface CreatedRoom {
        id: string
        join_code: string
        room_name: string
    }

    var roomName = $state('')
    var creating = $state(false)
    var error = $state('')

    var createdRoom = $state<CreatedRoom | null>(null)
    var copied = $state(false)

    function goBack() {
        if (history.length > 1) {
            history.back()
        } else {
            window.location.href = '/'
        }
    }

    async function createRoom() {
        if (!roomName.trim() || creating) return
        creating = true
        error = ''
        try {
            // join_code + admin_pin are auto-generated server-side by PocketBase.
            const record = await pb.collection('rooms').create<CreatedRoom>({
                room_name: roomName.trim(),
            })
            createdRoom = record
        } catch {
            error = 'สร้างห้องไม่สำเร็จ กรุณาลองอีกครั้ง'
        } finally {
            creating = false
        }
    }

    async function copy(text: string) {
        await navigator.clipboard.writeText(text)
        copied = true
        setTimeout(() => { copied = false }, 1500)
    }
</script>

<div class="flex flex-col min-h-dvh px-[5vw] pt-[max(3vh,env(safe-area-inset-top))] pb-[max(5vw,env(safe-area-inset-bottom))]">
    <button
        onclick={goBack}
        aria-label="ย้อนกลับ"
        class="w-[10vw] h-[10vw] sm:w-12 sm:h-12 flex items-center justify-center rounded-xl bg-white/15 text-white hover:bg-white/25 active:scale-95 transition"
    >
        <ChevronLeft class="w-[6vw] h-[6vw] sm:w-6 sm:h-6" />
    </button>

    {#if !createdRoom}
        <div class="flex-1 flex flex-col w-full max-w-md mx-auto">
            <div class="flex-1 flex flex-col items-center justify-center gap-[3vh] text-center">
                <span class="bg-white/15 p-[4vw] sm:p-5 rounded-2xl text-white">
                    <DoorOpen class="w-[8vw] h-[8vw] sm:w-8 sm:h-8" />
                </span>

                <div class="flex flex-col gap-[1vh]">
                    <h1 class="font-bold text-white text-[clamp(1.5rem,6vw,2.5rem)]">สร้างห้อง</h1>
                    <p class="text-gray-100 text-[clamp(1rem,4vw,1.25rem)]">ตั้งชื่อห้องเพื่อเริ่มจัดที่นั่ง</p>
                </div>

                <input
                    type="text"
                    autocomplete="off"
                    placeholder="ชื่อห้อง"
                    bind:value={roomName}
                    onkeydown={(e) => { if (e.key === 'Enter') createRoom() }}
                    class="w-full bg-white text-black placeholder-gray-400 rounded-2xl px-[5vw] py-[4vw] sm:px-6 sm:py-4 text-[clamp(1.125rem,4.5vw,1.375rem)] text-center font-bold outline-none focus:ring-4 focus:ring-white/40 transition"
                />

                {#if error}
                    <p class="text-red-200 text-[clamp(0.875rem,3.5vw,1rem)]">{error}</p>
                {/if}
            </div>

            <button
                onclick={createRoom}
                disabled={!roomName.trim() || creating}
                class="w-full bg-black text-white rounded-2xl py-[4vw] sm:py-4 font-bold text-[clamp(1.125rem,4.5vw,1.375rem)] flex items-center justify-center gap-2 active:scale-[0.98] transition disabled:opacity-40 disabled:active:scale-100 drop-shadow-2xl"
            >
                {#if creating}
                    <LoaderCircle class="w-[5vw] h-[5vw] sm:w-5 sm:h-5 animate-spin" />
                    กำลังสร้าง...
                {:else}
                    สร้างห้อง
                    <LogIn class="w-[5vw] h-[5vw] sm:w-5 sm:h-5" />
                {/if}
            </button>
        </div>
    {:else}
        <div class="flex-1 flex flex-col w-full max-w-md mx-auto">
            <div class="flex-1 flex flex-col items-center justify-center gap-[3vh] text-center">
                <span class="bg-white/15 p-[5vw] sm:p-6 rounded-3xl text-white">
                    <CircleCheckBig class="w-[10vw] h-[10vw] sm:w-12 sm:h-12" />
                </span>

                <div class="flex flex-col gap-[1vh]">
                    <h1 class="font-bold text-white text-[clamp(1.5rem,6vw,2.5rem)]">สร้างห้องสำเร็จ</h1>
                    <p class="text-gray-100 text-[clamp(1rem,4vw,1.25rem)]">{createdRoom.room_name}</p>
                </div>

                <div class="flex flex-col gap-[2vh] w-full">
                    <div class="w-full bg-white/15 backdrop-blur rounded-2xl p-[4vw] sm:p-5 text-white">
                        <p class="text-gray-100 text-[clamp(0.75rem,3vw,0.875rem)] uppercase tracking-widest">รหัสเข้าร่วม</p>
                        <div class="flex items-center justify-between gap-4 mt-[1vh]">
                            <p class="font-bold text-[clamp(1.75rem,8vw,2.5rem)] tracking-[0.3em]">{createdRoom.join_code}</p>
                            <button
                                onclick={() => copy(createdRoom!.join_code)}
                                aria-label="คัดลอกรหัสเข้าร่วม"
                                class="shrink-0 bg-white/15 rounded-xl p-[3vw] sm:p-3 flex items-center justify-center active:scale-95 transition"
                            >
                                {#if copied}
                                    <Check class="w-[5vw] h-[5vw] sm:w-5 sm:h-5 text-green-300" />
                                {:else}
                                    <Copy class="w-[5vw] h-[5vw] sm:w-5 sm:h-5" />
                                {/if}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="flex flex-col gap-[2vh] w-full">
                <a
                    href={`/join?stage=enter_code&code=${createdRoom.join_code}`}
                    class="w-full bg-black text-white rounded-2xl py-[4vw] sm:py-4 font-bold text-[clamp(1.125rem,4.5vw,1.375rem)] flex items-center justify-center gap-2 active:scale-[0.98] transition drop-shadow-2xl"
                >
                    เข้าร่วมห้อง
                    <LogIn class="w-[5vw] h-[5vw] sm:w-5 sm:h-5" />
                </a>
                <a
                    href="/"
                    class="w-full bg-white text-black rounded-2xl py-[4vw] sm:py-4 font-bold text-[clamp(1.125rem,4.5vw,1.375rem)] active:scale-[0.98] transition drop-shadow-2xl"
                >
                    กลับหน้าแรก
                </a>
            </div>
        </div>
    {/if}
</div>
